services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - customnet

networks:
  customnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET:-172.17.0.0/16}
          gateway: ${DOCKER_GATEWAY:-172.17.0.1}
